### ISSUE TITLE
crash in LeanplumMessageMatchResultMake

### ISSUE THREAD

**Issue by jaz-ah** [Leanplum/Leanplum-iOS-SDK#131]
## Expected Behavior
Not to crash

## Actual Behavior
Crash in this function as observed through Crashlytics

## Steps to Reproduce the Problem
No known reproducible steps yet - this is seen in our app with Crashlytics and always happens when the app is in the foreground:

```
#0Crashed: com.apple.main-threadEXC_BAD_ACCESS KERN_INVALID_ADDRESS 0x000001a1b72ba041 Raw Text
--
0 | libobjc.A.dylib | objc_msgSend + 8
1 | CoreFoundation | -[__NSDictionaryM setObject:forKeyedSubscript:] + 576
2 | Leanplum | LeanplumMessageMatchResultMake + 36676
3 | Leanplum | leanplumExceptionHandler + 90972
4 | Leanplum | leanplumExceptionHandler + 86476
5 | Leanplum | leanplumExceptionHandler + 85696
6 | Leanplum | Leanplum_FileMD5HashCreateWithPath + 33292
7 | Leanplum | Leanplum_FileMD5HashCreateWithPath + 29164
8 | Foundation | -[__NSObserver _doit:] + 312
9 | CoreFoundation | __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 20
10 | CoreFoundation | _CFXRegistrationPost + 420
11 | CoreFoundation | ___CFXNotificationPost_block_invoke + 60
12 | CoreFoundation | -[_CFXNotificationRegistrar find:object:observer:enumerator:] + 1408
13 | CoreFoundation | _CFXNotificationPost + 380
14 | Foundation | -[NSNotificationCenter postNotificationName:object:userInfo:] + 68
15 | UIKit | __47-[UIApplication _applicationDidEnterBackground]_block_invoke + 268
16 | UIKit | +[UIViewController _performWithoutDeferringTransitions:] + 128
17 | UIKit | -[UIApplication _applicationDidEnterBackground] + 112
18 | UIKit | -[__UICanvasLifecycleMonitor_Compatability deactivateEventsOnly:withContext:forceExit:completion:] + 996
19 | UIKit | -[_UIApplicationCanvas forceDeactivateWithTransitionContext:completion:] + 76
20 | UIKit | -[UIApplication workspaceShouldExit:withTransitionContext:] + 272
21 | libdispatch.dylib | _dispatch_client_callout + 16
22 | libdispatch.dylib | _dispatch_block_invoke_direct$VARIANT$mp + 288
23 | FrontBoardServices | __FBSSERIALQUEUE_IS_CALLING_OUT_TO_A_BLOCK__ + 36
24 | FrontBoardServices | -[FBSSerialQueue _performNext] + 404
25 | FrontBoardServices | -[FBSSerialQueue _performNextFromRunLoopSource] + 56
26 | CoreFoundation | __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 24
27 | CoreFoundation | __CFRunLoopDoSource0 + 88
28 | CoreFoundation | __CFRunLoopDoSources0 + 204
29 | CoreFoundation | __CFRunLoopRun + 1048
30 | CoreFoundation | CFRunLoopRunSpecific + 436
31 | GraphicsServices | GSEventRunModal + 100
32 | UIKit | UIApplicationMain + 236
33 | Activehours | CAShapeLayer+Activehours.swift line 5main
34 | libdyld.dylib | start + 4
```

## Specifications

  - Version: 2.0.5 of the leanplum sdk
  - Platform: iOS
  - Subsystem:

**Comment by jaz-ah** [comment]
@alexisoyama any thoughts on this one?

**Comment by benmarten** [comment]
Hi,

looks like one of the arguments might be null. All crashes should be caught by our global try/catch handlers...

To understand where the crash exactly happens, can you please symbolicate the stacktrace?
Here's the dysim: https://storage.googleapis.com/leanplum-sdk-release/Leanplum-2.0.5-SDK-mapping.zip
To my understanding crashlytics can do that for you, once you upload the file...

**Comment by jaz-ah** [comment]
@benmarten I uploaded the dsyms but not getting any further symbolication than what outputs above...

**Comment by jaz-ah** [comment]
@benmarten any update? I got a similar crash in the same function:
```

#0Crashed: com.apple.main-threadEXC_BAD_ACCESS KERN_INVALID_ADDRESS 0x0000000000000000 Raw Text
--
0 | CoreFoundation | -[__NSDictionaryM removeAllObjects] + 552
1 | Leanplum | LeanplumMessageMatchResultMake + 39152
2 | Leanplum | leanplumExceptionHandler + 89648
3 | Leanplum | LeanplumMessageMatchResultMake + 119968
4 | libdispatch.dylib | _dispatch_call_block_and_release + 24
5 | libdispatch.dylib | _dispatch_client_callout + 16
6 | libdispatch.dylib | _dispatch_main_queue_callback_4CF$VARIANT$mp + 1016
7 | CoreFoundation | __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 12
8 | CoreFoundation | __CFRunLoopRun + 2012
9 | CoreFoundation | CFRunLoopRunSpecific + 436
10 | GraphicsServices | GSEventRunModal + 100
11 | UIKit | UIApplicationMain + 236
12 | Activehours | CAShapeLayer+Activehours.swift line 5main
13 | libdyld.dylib | start + 4
```

**Comment by benmarten** [comment]
@jaz-ah Please forgive my delayed response.
Can you please share the full crashlog? Then I can try to desymbolicate it... We need to have the Binary Image information, please share a crashlog similar to: https://gist.github.com/benmarten/671a0dc6f5cc0bd6f52dca61a627d579
On which Leanplum SDK version are you?

**Comment by jaz-ah** [comment]
@benmarten still on version 2.0.5 of the Leanplum SDK. 
here's one of the crashlogs: https://gist.github.com/jaz-ah/1f58b04cc30b81e045696103d1940ed2

**Comment by benmarten** [comment]
Ok thanks. No I was able to desymbolicate it, following this tutorial: https://gist.github.com/bmatcuk/c55a0dd4f8775a3a2c5a

`atos -o Leanplum.framework.dSYM/Contents/Resources/DWARF/Leanplum -l 0x103c38000 0x0000000103c733ec 0x0000000103c66c70 0x0000000103c65ae0 0x0000000103c657d4 0x0000000103c48434 0x0000000103c47414`

```
Thread 0 name:
Thread 0 Crashed:
0   libobjc.A.dylib                 0x000000018426c428 objc_msgSend + 8
1   CoreFoundation                  0x000000018504cad0 -[__NSDictionaryM setObject:forKeyedSubscript:] + 576 (NSDictionaryM_Common.h:31)
2   Leanplum                        0x0000000103c733ec +[LPEventCallbackManager addEventCallbackAt:onSuccess:onError:] (in Leanplum) (LPEventCallbackManager.m:101)
3   Leanplum                        0x0000000103c66c70 -[LeanplumRequest sendEventually] (in Leanplum) (LeanplumRequest.m:476)
4   Leanplum                        0x0000000103c65ae0 -[LeanplumRequest sendRequests:] (in Leanplum) (LeanplumRequest.m:302)
5   Leanplum                        0x0000000103c657d4 -[LeanplumRequest sendIfConnected] (in Leanplum) (LeanplumRequest.m:259)
6   Leanplum                        0x0000000103c48434 __17+[Leanplum pause]_block_invoke (in Leanplum) (Leanplum.m:1176)
7   Leanplum                        0x0000000103c47414 __59+[Leanplum startWithUserId:userAttributes:responseHandler:]_block_invoke_2.702 (in Leanplum) (Leanplum.m:1044)
8   Foundation                      0x0000000185905ec4 -[__NSObserver _doit:] + 312 (NSNotification.m:324)
9   CoreFoundation                  0x0000000184fa113c __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 20 (CFNotificationCenter.c:661)
10  CoreFoundation                  0x0000000184fa06dc _CFXRegistrationPost + 420 (CFNotificationCenter.c:163)
11  CoreFoundation                  0x0000000184fa0440 ___CFXNotificationPost_block_invoke + 60 (CFNotificationCenter.c:1060)
12  CoreFoundation                  0x000000018501de24 -[_CFXNotificationRegistrar find:object:observer:enumerator:] + 1408 (CFXNotificationRegistrar.m:163)
13  CoreFoundation                  0x0000000184ed6d60 _CFXNotificationPost + 380 (CFNotificationCenter.c:1057)
14  Foundation                      0x0000000185903348 -[NSNotificationCenter postNotificationName:object:userInfo:] + 68 (NSNotification.m:543)
15  UIKit                           0x000000018e833a9c __47-[UIApplication _applicationDidEnterBackground]_block_invoke + 268 (UIApplication.m:6028)
16  UIKit                           0x000000018e93fb14 +[UIViewController _performWithoutDeferringTransitions:] + 128 (UIViewController.m:6623)
17  UIKit                           0x000000018e8338f4 -[UIApplication _applicationDidEnterBackground] + 112 (UIApplication.m:6015)
18  UIKit                           0x000000018eacb1e0 -[__UICanvasLifecycleMonitor_Compatability deactivateEventsOnly:withContext:forceExit:completion:] + 996 (_UICanvasLifecycleMonitor.m:390)
19  UIKit                           0x000000018f24f838 __82-[_UIApplicationCanvas _transitionLifecycleStateWithTransitionContext:completion:]_block_invoke + 380 (_UIApplicationCanvas.m:0)
20  UIKit                           0x000000018f24f664 -[_UIApplicationCanvas _transitionLifecycleStateWithTransitionContext:completion:] + 448 (_UIApplicationCanvas.m:156)
21  UIKit                           0x000000018efbd2cc __125-[_UICanvasLifecycleSettingsDiffAction performActionsForCanvas:withUpdatedScene:settingsDiff:fromSettings:transitionContext:]_block_invoke + 220 (_UICanvasLifecycleSettingsDiffAction.m:211)
22  UIKit                           0x000000018f1563cc _performActionsWithDelayForTransitionContext + 112 (_UICanvasSettingsDiffAction.m:34)
23  UIKit                           0x000000018efbd17c -[_UICanvasLifecycleSettingsDiffAction performActionsForCanvas:withUpdatedScene:settingsDiff:fromSettings:transitionContext:] + 252 (_UICanvasLifecycleSettingsDiffAction.m:182)
24  UIKit                           0x000000018eda1760 -[_UICanvas scene:didUpdateWithDiff:transitionContext:completion:] + 364 (_UICanvas.m:517)
25  UIKit                           0x000000018ec432a8 -[UIApplicationSceneClientAgent scene:handleEvent:withCompletion:] + 468 (UIApplicationSceneClientAgent.m:77)
26  FrontBoardServices              0x00000001876d2ca4 __80-[FBSSceneImpl updater:didUpdateSettings:withDiff:transitionContext:completion:]_block_invoke.362 + 212 (FBSSceneImpl.m:571)
27  libdispatch.dylib               0x000000018498ea14 _dispatch_client_callout + 16 (object.m:502)
28  libdispatch.dylib               0x0000000184996200 _dispatch_block_invoke_direct$VARIANT$mp + 288 (queue.c:3025)
29  FrontBoardServices              0x00000001877067f8 __FBSSERIALQUEUE_IS_CALLING_OUT_TO_A_BLOCK__ + 36 (FBSSerialQueue.m:164)
30  FrontBoardServices              0x000000018770649c -[FBSSerialQueue _performNext] + 404 (FBSSerialQueue.m:196)
31  FrontBoardServices              0x0000000187706a38 -[FBSSerialQueue _performNextFromRunLoopSource] + 56 (FBSSerialQueue.m:232)
32  CoreFoundation                  0x0000000184fb777c __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 24 (CFRunLoop.c:1982)
33  CoreFoundation                  0x0000000184fb76fc __CFRunLoopDoSource0 + 88 (CFRunLoop.c:2017)
34  CoreFoundation                  0x0000000184fb6f84 __CFRunLoopDoSources0 + 204 (CFRunLoop.c:2053)
35  CoreFoundation                  0x0000000184fb4b5c __CFRunLoopRun + 1048 (CFRunLoop.c:2920)
36  CoreFoundation                  0x0000000184ed4c58 CFRunLoopRunSpecific + 436 (CFRunLoop.c:3245)
37  GraphicsServices                0x0000000186d80f84 GSEventRunModal + 100 (GSEvent.c:2245)
38  UIKit                           0x000000018e62d5c4 UIApplicationMain + 236 (UIApplication.m:3956)
39  Activehours                     0x0000000102d5ed28 main + 56 (CAShapeLayer+Activehours.swift:5)
40  libdyld.dylib                   0x00000001849f456c start + 4
```

Note, the lines are off by 1 line, but I've seen that before, so I don't think that's an issue here...

So it looks like the crash is happening here: https://github.com/Leanplum/Leanplum-iOS-SDK/blob/develop/Leanplum-SDK/Classes/LPEventCallbackManager.m#L100

We'll investigate the issue now...

**Comment by benmarten** [comment]
Looks to me, as if the application has just entered the background.
It looks like the object might have been already release or sth? or maybe the application is not allowed to access that memory address anymore once in background?

**Comment by benmarten** [comment]
Possible fix: https://github.com/Leanplum/Leanplum-iOS-SDK/pull/135
https://stackoverflow.com/questions/22653822/nsdictionarym-setobjectforkey-exc-bad-access-crash?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa

**Comment by e7mac** [comment]
@jaz-ah we just released a new version today

**Comment by jaz-ah** [comment]
ok great we'll give it a try.

**Comment by jazsoftware** [comment]
@benmarten looks like crash isn't fixed w/ most recent version of the lp sdk (2.0.6):
```

#0Crashed: com.apple.main-threadEXC_BAD_ACCESS KERN_INVALID_ADDRESS 0x0000000000000a8a Raw Text
--
0 | libobjc.A.dylib | objc_msgSend + 8
1 | CoreFoundation | -[__NSDictionaryM setObject:forKeyedSubscript:] + 460
2 | Leanplum | LeanplumMessageMatchResultMake + 36820
3 | Leanplum | leanplumExceptionHandler + 90536
4 | Leanplum | leanplumExceptionHandler + 86072
5 | Leanplum | leanplumExceptionHandler + 85292
6 | Leanplum | Leanplum_FileMD5HashCreateWithPath + 33304
7 | Leanplum | Leanplum_FileMD5HashCreateWithPath + 29176
8 | Foundation | -[__NSObserver _doit:] + 312
9 | CoreFoundation | __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 20
10 | CoreFoundation | _CFXRegistrationPost + 428
11 | CoreFoundation | ___CFXNotificationPost_block_invoke + 216
12 | CoreFoundation | -[_CFXNotificationRegistrar find:object:observer:enumerator:] + 1408
13 | CoreFoundation | _CFXNotificationPost + 384
14 | Foundation | -[NSNotificationCenter postNotificationName:object:userInfo:] + 68
15 | UIKit | __47-[UIApplication _applicationDidEnterBackground]_block_invoke + 268
16 | UIKit | +[UIViewController _performWithoutDeferringTransitions:] + 112
17 | UIKit | -[UIApplication _applicationDidEnterBackground] + 96
18 | UIKit | -[__UICanvasLifecycleMonitor_Compatability deactivateEventsOnly:withContext:forceExit:completion:] + 1000
19 | UIKit | __82-[_UIApplicationCanvas _transitionLifecycleStateWithTransitionContext:completion:]_block_invoke + 376
20 | UIKit | -[_UIApplicationCanvas _transitionLifecycleStateWithTransitionContext:completion:] + 432
21 | UIKit | __125-[_UICanvasLifecycleSettingsDiffAction performActionsForCanvas:withUpdatedScene:settingsDiff:fromSettings:transitionContext:]_block_invoke + 220
22 | UIKit | _performActionsWithDelayForTransitionContext + 112
23 | UIKit | -[_UICanvasLifecycleSettingsDiffAction performActionsForCanvas:withUpdatedScene:settingsDiff:fromSettings:transitionContext:] + 248
24 | UIKit | -[_UICanvas scene:didUpdateWithDiff:transitionContext:completion:] + 368
25 | UIKit | -[UIApplicationSceneClientAgent scene:handleEvent:withCompletion:] + 468
26 | FrontBoardServices | __80-[FBSSceneImpl updater:didUpdateSettings:withDiff:transitionContext:completion:]_block_invoke.362 + 212
27 | libdispatch.dylib | _dispatch_client_callout + 16
28 | libdispatch.dylib | _dispatch_block_invoke_direct$VARIANT$armv81 + 216
29 | FrontBoardServices | __FBSSERIALQUEUE_IS_CALLING_OUT_TO_A_BLOCK__ + 36
30 | FrontBoardServices | -[FBSSerialQueue _performNext] + 404
31 | FrontBoardServices | -[FBSSerialQueue _performNextFromRunLoopSource] + 56
32 | CoreFoundation | __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 24
33 | CoreFoundation | __CFRunLoopDoSources0 + 276
34 | CoreFoundation | __CFRunLoopRun + 1204
35 | CoreFoundation | CFRunLoopRunSpecific + 552
36 | GraphicsServices | GSEventRunModal + 100
37 | UIKit | UIApplicationMain + 236
38 | Activehours | CAShapeLayer+Activehours.swift line 5main

```

**Comment by jaz-ah** [comment]
@benmarten looks like crash isn't fixed w/ most recent version of the lp sdk (2.0.6):
```

#0Crashed: com.apple.main-threadEXC_BAD_ACCESS KERN_INVALID_ADDRESS 0x0000000000000a8a Raw Text
--
0 | libobjc.A.dylib | objc_msgSend + 8
1 | CoreFoundation | -[__NSDictionaryM setObject:forKeyedSubscript:] + 460
2 | Leanplum | LeanplumMessageMatchResultMake + 36820
3 | Leanplum | leanplumExceptionHandler + 90536
4 | Leanplum | leanplumExceptionHandler + 86072
5 | Leanplum | leanplumExceptionHandler + 85292
6 | Leanplum | Leanplum_FileMD5HashCreateWithPath + 33304
7 | Leanplum | Leanplum_FileMD5HashCreateWithPath + 29176
8 | Foundation | -[__NSObserver _doit:] + 312
9 | CoreFoundation | __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 20
10 | CoreFoundation | _CFXRegistrationPost + 428
11 | CoreFoundation | ___CFXNotificationPost_block_invoke + 216
12 | CoreFoundation | -[_CFXNotificationRegistrar find:object:observer:enumerator:] + 1408
13 | CoreFoundation | _CFXNotificationPost + 384
14 | Foundation | -[NSNotificationCenter postNotificationName:object:userInfo:] + 68
15 | UIKit | __47-[UIApplication _applicationDidEnterBackground]_block_invoke + 268
16 | UIKit | +[UIViewController _performWithoutDeferringTransitions:] + 112
17 | UIKit | -[UIApplication _applicationDidEnterBackground] + 96
18 | UIKit | -[__UICanvasLifecycleMonitor_Compatability deactivateEventsOnly:withContext:forceExit:completion:] + 1000
19 | UIKit | __82-[_UIApplicationCanvas _transitionLifecycleStateWithTransitionContext:completion:]_block_invoke + 376
20 | UIKit | -[_UIApplicationCanvas _transitionLifecycleStateWithTransitionContext:completion:] + 432
21 | UIKit | __125-[_UICanvasLifecycleSettingsDiffAction performActionsForCanvas:withUpdatedScene:settingsDiff:fromSettings:transitionContext:]_block_invoke + 220
22 | UIKit | _performActionsWithDelayForTransitionContext + 112
23 | UIKit | -[_UICanvasLifecycleSettingsDiffAction performActionsForCanvas:withUpdatedScene:settingsDiff:fromSettings:transitionContext:] + 248
24 | UIKit | -[_UICanvas scene:didUpdateWithDiff:transitionContext:completion:] + 368
25 | UIKit | -[UIApplicationSceneClientAgent scene:handleEvent:withCompletion:] + 468
26 | FrontBoardServices | __80-[FBSSceneImpl updater:didUpdateSettings:withDiff:transitionContext:completion:]_block_invoke.362 + 212
27 | libdispatch.dylib | _dispatch_client_callout + 16
28 | libdispatch.dylib | _dispatch_block_invoke_direct$VARIANT$armv81 + 216
29 | FrontBoardServices | __FBSSERIALQUEUE_IS_CALLING_OUT_TO_A_BLOCK__ + 36
30 | FrontBoardServices | -[FBSSerialQueue _performNext] + 404
31 | FrontBoardServices | -[FBSSerialQueue _performNextFromRunLoopSource] + 56
32 | CoreFoundation | __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 24
33 | CoreFoundation | __CFRunLoopDoSources0 + 276
34 | CoreFoundation | __CFRunLoopRun + 1204
35 | CoreFoundation | CFRunLoopRunSpecific + 552
36 | GraphicsServices | GSEventRunModal + 100
37 | UIKit | UIApplicationMain + 236
38 | Activehours | CAShapeLayer+Activehours.swift line 5main

```

**Comment by rpassis** [comment]
I think this crash is related to multiple threads modifying the mutable array concurrently - you should probably synchronise the read/write of that property.

**Comment by jaz-ah** [comment]
not seeing this specific crash w/ leanplum sdk 2.2.1 , will file a bug for the new crash we're seeing.
